"""Module-style facade over a lazily-built :class:`VkRegistry`.

Lets callers write ``vk.vkCreateInstance(...)`` / ``vk.VkInstance`` /
``vk.VK_SUCCESS`` after a single ``from volkano import vk`` — no
explicit ``build_registry()`` call. The registry is built on first
attribute access and cached for the rest of the process, so
``import vk`` itself is essentially free.

A companion stub file (``vk.pyi``) generated by
:mod:`volkano.stub` declares every name with light type
annotations and command parameter signatures, so IDEs surface
autocomplete and parameter hints even though all names are resolved
dynamically at runtime.

Customising the singleton
-------------------------

If you need a non-default library path (or want to disable lazy
binding), call :func:`configure` *before* the first attribute access::

    from volkano import vk
    vk.configure(source='xml/vk.xml', library='/opt/vulkan/lib/libvulkan.so.1')
    inst = vk.VkInstance()

Once any attribute has been read, :func:`configure` raises — the
process-wide singleton is locked to whatever parameters were active
when it was first built. Pass ``reset=True`` to forcibly discard the
existing registry and rebuild with new settings (rare; only useful in
tests or REPL experimentation).
"""

from __future__ import annotations

from typing import Any


# Lazy singleton. ``None`` means "not built yet"; calling any of the
# module-level functions below that need a registry triggers
# construction with the parameters last passed to :func:`configure`
# (or the defaults if :func:`configure` was never called).
_registry: Any = None
_build_kwargs: dict = {'library': True}


def configure(*, source: Any = None, library: Any = True,
              refresh: bool = False, reset: bool = False) -> None:
    """Set the parameters for the lazily-built registry singleton.

    Must be called *before* any other attribute is read from this
    module (which would trigger construction with the previous
    parameters). Pass ``reset=True`` to discard a previously-built
    singleton — useful in interactive sessions where you want to swap
    in a different ``vk.xml`` or library without restarting Python.
    """
    global _registry, _build_kwargs
    if _registry is not None and not reset:
        raise RuntimeError(
            "volkano.vk has already been built. Pass reset=True to "
            "discard the current singleton and rebuild with new parameters.")
    _registry = None
    _build_kwargs = {'source': source, 'library': library, 'refresh': refresh}


def get_registry():
    """Return the underlying :class:`VkRegistry`, building it on first call."""
    global _registry
    if _registry is None:
        from .vulkan_stdlib import build_registry
        _registry = build_registry(**_build_kwargs)
    return _registry


def __getattr__(name: str) -> Any:
    """PEP 562: invoked when ``vk.<name>`` misses the module namespace.

    Delegates to the singleton registry's attribute access (which in
    turn force-resolves the entry through the cache). Names starting
    with underscore go through the normal Python attribute path and
    never trigger registry resolution, so introspection tools probing
    for ``__loader__`` etc. don't accidentally force the build.
    """
    if name.startswith('_'):
        raise AttributeError(name)
    return getattr(get_registry(), name)


def __dir__() -> list[str]:
    """Surface every registered name to ``dir(vk)`` and tab completion."""
    base = {'configure', 'get_registry'}
    base.update(name for name in dir(get_registry())
                if not name.startswith('_'))
    return sorted(base)
